# Generated by Django 2.1 on 2019-04-30 14:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=2000)),
                ('type', models.CharField(choices=[('ลากิจ', 'ลากิจ'), ('ลาป่วย', 'ลาป่วย')], default='ลากิจ', max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('approve_status', models.CharField(choices=[('อนุมัติ', 'อนุมัติ'), ('รอการดำเนินการ', 'รอการดำเนินการ'), ('ไม่อนุมติ', 'ไม่อนุมัติ')], max_length=10)),
                ('create_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
