# Generated by Django 2.1 on 2019-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approve_status',
            field=models.CharField(choices=[('อนุมัติ', 'อนุมัติ'), ('รอการดำเนินการ', 'รอการดำเนินการ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ')], default='ไม่อนุมัติ', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
